onlyBuiltDependencies:
  - '@prisma/engines'
  - esbuild
  - msgpackr-extract
  - prisma
  - workerd

fetchTimeout: 600000
networkConcurrency: 4
fetchRetries: 8
allowBuilds:
  '@prisma/engines': true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  workerd: true
  unrs-resolver: true
